### ISSUE TITLE
Doesn't work on node 19

### ISSUE THREAD

**Issue by shafouz** [CodeIntelligenceTesting/jazzer.js#516]
Jazzer gives the following error on node 19:
```
TypeError: firstArgument.includes is not a function
    at Hook.beforeHook [as hookFunction] (/app/node_modules/@jazzer.js/bug-detectors/internal/path-traversal.ts:136:22)
    at module.<computed> (/app/node_modules/@jazzer.js/hooking/manager.ts:240:10)
    at getSource (node:internal/modules/esm/load:38:20)
    at ESMLoader.defaultLoad (node:internal/modules/esm/load:94:38)
    at ESMLoader.load (node:internal/modules/esm/loader:342:43)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:207:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:231:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:184:34)
```
it works normally on node 18 and 16

Minimal steps to reproduce:
```Dockerfile
FROM node:19

WORKDIR /app
RUN npm i --save-dev @jazzer.js/core
COPY test_fuzz.js package.json /app/
ENTRYPOINT ["npx", "jazzer", "./test_fuzz.js"]
```

```json
{
  "name": "test_fuzz",
  "version": "1.0.0",
  "description": "Examples of fuzz tests for Jazzer.js",
  "type": "module"
}
```
```javascript
/**
 * @param { Buffer } data
 */
export function fuzz(data) {
  let sum = data.toString();

  if (sum == "2") {
    throw Error("asdasd");
  }
}
```

**Comment by shafouz** [comment]
the error was because i was using esm instead of the require() one

**Comment by bertschneider** [comment]
Thx for the update! ESM support is still on the todo list.
