### ISSUE TITLE
Issues running jazzer in node v14

### ISSUE THREAD

**Issue by karfau** [CodeIntelligenceTesting/jazzer.js#641]
The `engine` in package.json claims that nodejs version `>=14` is supported/required. But when using the most recent version of Node 14 (as part of a test) I get the following output:

```
     TypeError: Object.hasOwn is not a function
       at node_modules/@jazzer.js/core/options.ts:207:15
           at Array.forEach (<anonymous>)
       at mergeOptions (node_modules/@jazzer.js/core/options.ts:205:31)
       at node_modules/@jazzer.js/core/options.ts:179:11
           at Array.reduce (<anonymous>)
       at buildOptions (node_modules/@jazzer.js/core/options.ts:176:4)
       at loadConfig (node_modules/@jazzer.js/jest-runner/config.ts:52:21)
```

https://github.com/xmldom/xmldom/actions/runs/6452742416/job/17515178816#step:7:64

The GitHub action workflow that is used for testing in the jazzer.js repository is using node v16.

Should the value in the engines field be bumped or are you still trying to support node v14?

**Comment by oetr** [comment]
Thanks for reporting this!
I think we do want to support node v14, so we'll take a look.
